### ISSUE TITLE
The check export contains additional fields only for UI

### ISSUE THREAD

**Issue by dgildeh** [outlyerapp/outlyer-cli#1]
If you export a check from the account using the export command you get the following check YAML:

```
author:
  fullName: David Gildeh
  id: auth0|59e0a1d8f204d4121f24134d
command: kube-state-metrics.py
created: "2018-08-15T22:48:01.581Z"
description: Scrapes key Kubernetes metrics from Kube State Metrics
disabled: true
env: []
handler: Native
icon: integration--docker
id: 02b23ed3-5050-4ea8-87f3-d6bc696b8348
interval: 30
modified: "2018-08-15T22:48:39.317Z"
name: kube-state-metrics
plugins:
- kube-state-metrics.py
selectors: []
title: 'Kubernetes: Kube State Metrics'
```
author, created, id, modified are all internal fields for UI and shouldn't be in the check YAML. Please remove these fields, if the API requires these fields to be there when posting a new check then please speak to API team to fix the API so these aren't required when creating a new check.
